name: python-library-1
version: 1.1.0
versioned_at: 2026-10-08 17:57
description: Reusable conventions for Python libraries with stable public APIs.
entrypoint: README.md
dependencies:
- name: meta
  version: 2.0.2
  constraint: at_least
- name: process
  version: 3.0.2
  constraint: at_least
- name: repository-1
  version: 2.0.2
  constraint: at_least
- name: python-1
  version: 2.0.2
  constraint: at_least
